### PR TITLE
Fix MAC address generation

### LINKED ISSUE #65: Improve android id generation
Improve how we generate android id and double check what is the required length.

See https://github.com/leikoilja/glocaltokens/pull/56#discussion_r608499319

### PR DESCRIPTION
**Pull request by KapJI**
Generate 12 random chars.

Closes #65

### CODE REVIEW

**Comment by leikoilja** [comment]
Are we sure it's 12 chars? 🤔

**Comment by leikoilja** [comment]
Just tried on friend's samsung s10+ and serial number is 11 chars

**Comment by KapJI** [comment]
It should be 6 bytes: https://en.wikipedia.org/wiki/MAC_address

**Comment by leikoilja** [comment]
From some [old commit](https://github.com/simon-weber/gmusicapi/commit/30f5080202aaa615ef31b771b1fd0add5b16a315#diff-2bde95b4686ecd42076dd54288ec9957bd7d906f328caade770c20c4ea69c2fcR37) on `gpsoauth` 
image

**Comment by KapJI** [comment]
Why do you call it a mac address then? 🙂
If we can find an example, we can follow its format.

**Comment by KapJI** [comment]
Let's generate 16 chars ID.

**Comment by leikoilja** [comment]
It was some one the stuff reused from `https://gist.github.com/rithvikvibhu/952f83ea656c6782fbd0f1645059055d` calling it mac

**Review by leikoilja — APPROVED** [review]

**Pull request merged**
