### PR TITLE
Enable distributing type info with a package

### PR DESCRIPTION
**Pull request by leikoilja**
To make the package [PEP-561](https://www.python.org/dev/peps/pep-0561/) compliant this PR 
enables distributing typing info
 
Required by: https://github.com/leikoilja/ha-google-home/pull/88

### CODE REVIEW

**Comment by leikoilja** [comment]
@KapJI, please take a look

**Comment by KapJI** [comment]
You also need to create empty `py.typed` file in package root.

**Comment by KapJI** [comment]
Also do you have `mypy` in CI jobs?

**Comment by leikoilja** [comment]
No, there is no `mypy` check in CI jobs. I ll add a separate issue to introduce `poetry` in this repo and enable `mypy` correspondingly to what you have done in `ha-google-home` :)

**Review by KapJI — APPROVED** [review]
Make sure you run `mypy` before release the new package, otherwise errors can be propogated to packages which use `glocaltoken`.

**Comment by leikoilja** [comment]
hmmm, why would that be a reason, @KapJI? You mean `typing` errors? They shouldn't break anything, right?

**Comment by KapJI** [comment]
They can break type checking. Basically `mypy` will check all dendencies which are marked as typed with `py.typed`.

**Comment by KapJI** [comment]
@leikoilja this seems stuck. Is there anything blocking you?

**Comment by leikoilja** [comment]
yeh, took a little break, but now i m back. Also had started on setting up `poetry` for this repo and it went down with TONS of errors. Couldn't really understand whether it's because of my experimental `arm m1 mac` that has some glitches here and there or something else. WIll pick it up soon on my ubuntu and proceed with `poetry` :)

**Comment by leikoilja** [comment]
@KapJI can't find any useful information in docs, but now that the `poetry` is in place, do we need to explicitly note something like `package_data={"glocaltokens": ["py.typed"]}` that used to be in `setup.py`?

**Comment by KapJI** [comment]
Yes, you can do this using `include`: [docs](https://python-poetry.org/docs/pyproject/#include-and-exclude).
Also add `Typing :: Typed` classifier.

**Review by KapJI — APPROVED** [review]
Yeah, should be it :)

**Pull request merged**
