### PR TITLE
Documentation generator

### PR DESCRIPTION
**Pull request by ArnyminerZ**
Implemented a Github Workflow for generating documentation through Sphinx to Github Pages.

Note: I believe Github Pages should be enabled by @leikoilja

### CODE REVIEW

**Comment by ArnyminerZ** [comment]
Still working on this. Openned PR just for reference.

**Comment by leikoilja** [comment]
Ou wow! This sounds amazing! 🤩💥 Have never tried proper documentation generators like Sphinx before, it's going to be great! 
I have just enabled GitHub pages for directory /docs (that we don't have yet) 😂🤷‍♂️ let me know if I can help anyhow 🤩💥

**Comment by leikoilja** [comment]
@ArnyminerZ, sorry i don't mean to undervalue what you have started with Sphinx, but have you by chance considered [Slate](https://github.com/slatedocs/slate)?  That also looks pretty sexy 😄

**Comment by ArnyminerZ** [comment]
We can use Slate. I chose Sphinx because it was the first one that I found. Will start researching for Slate implementation

**Comment by leikoilja** [comment]
I'm very open to any of those! If you have interested in implementing - it's up to you whichever you want to play with :) 💥

**Comment by leikoilja** [comment]
Haha, sorry, @ArnyminerZ, i hope i didn't discourage you from implementing doc generator 😄

**Comment by ArnyminerZ** [comment]
No, don't worry, I have it in mind, but my repo was getting such a mess, and I deleted it and created a new fork 😅 
Will work on that when I have a bit more time.

**Comment by leikoilja** [comment]
Haha, no worries at all 💯  Thanks 🥇

**Pull request closed without merging**
