### PR TITLE
Grpcio tools version

### PR DESCRIPTION
**Pull request by ArnyminerZ**
I've had problems installing `grpcio` on some devices because not setting a version on `grpcio-tools` installs the latest one, which is incompatible with `grpcio==1.31.0`. Adding this should fix this, and it's not a big change.

*Note: I can't figure out why there are that much commits, but it only updates one file, so I think it doesn't matter.*

### CODE REVIEW

**Comment by DurgNomis-drol** [comment]
This issue is know already

And `grpcio-tools` still need `g++` and `linux-headers` to compile on alpine. Which is not in the official release of HA.

**Comment by ArnyminerZ** [comment]
> And `grpcio-tools` still need `g++` and `linux-headers` to compile on alpine. Which is not in the official release of HA.

And isn't there a way to install those packages when the library is installed, maybe through `setup.py`? 🤔

**Comment by DurgNomis-drol** [comment]
As far as i know there is not.
I don't think that HA allows integrations it install non python dependencies.

It have to be done by HA when the alpine image is build.

**Comment by DurgNomis-drol** [comment]
See #11 for more details

**Comment by DurgNomis-drol** [comment]
And [Here](https://github.com/leikoilja/ha-glocaltokens/issues/14)

**Comment by ArnyminerZ** [comment]
Yes, the long compilation times for RPi are a bit unevitable, since it's a quite low-power computer... Even that, what I meant is that python installs `grpcio-tools` version `1.35.0` if version is not set. This version is incompatible with `grpcio` version `1.31.0`, which is the required by `glocaltokens`, and it's required to install `grpcio-tools==1.31.0` manually.

**Comment by DurgNomis-drol** [comment]
This is already know, but this problem has to be fixed on HA side. This will also remove the issue of long build times for `grpio-tools` on RPI. Because `grpcio` and `grpcio-tools` will then have precompiled build wheels from HA. And this problem also exists on other systems then RPI if they run on alpine. HomeassistantOS is based on buildroot and not Alpine.

But yes `grpcio-tools` should be changed to `grpcio-tools` version that matches the already installed version of `grpcio` in HA.

I don't not know the reason why HA does not ship with latest version of `grpcio`.

@leikoilja Have already opened an issue over at HA to fix these things. Until then, you would have to install it manually.

Also you have to fix your commit to only include the change of dependency for `grpcio.tools` :smile:

**Review by leikoilja — APPROVED** [review]
That's a great find, thank you, @ArnyminerZ.

**Comment by leikoilja** [comment]
It is indeed an issue that we need to manually build `grpcio` and `grpcio-tools` outside the home assistant. That takes time and is inconvenient for most users, but before HA solves that we'll have to just manually install those. If I understood it correcntly they have locked the version down for a reason, i believe the newest versions were failing to build on `arm`:

> 
> gRPC 1.32+ currently causes issues on ARMv7, see:
> https://github.com/home-assistant/core/issues/40148

Here is a general issue where we can keep the discussion regarding `grpcio` - https://github.com/leikoilja/glocaltokens/issues/11

**Pull request merged**
